### ISSUE TITLE
add more css to header

### ISSUE THREAD

**Issue by utkarshsingx** [utkarshsingx/baratie#3]

**Comment by yr1404** [comment]
I could work on adding more CSS. Can you assign this to me?

**Comment by utkarshsingx** [comment]
> I could work on adding more CSS. Can you assign this to me?

Ok I will assign this to you.

**Comment by yr1404** [comment]
I have made few changes:

On hover borders to li links  
![Screenshot from 2023-10-07 01-07-42](https://github.com/utkarshsingx/baratie/assets/106465753/4845dcdd-da96-4ce7-93ea-075a508138b0)  
  
On hover changes to login button
![image](https://github.com/utkarshsingx/baratie/assets/106465753/cfdba4eb-7d5a-487d-86a4-4c1e17f49dc0)

The overall header looks like this(with box shadow)
![image](https://github.com/utkarshsingx/baratie/assets/106465753/fcb1a26a-d81e-43c4-8572-a4541a388a3f)

Do you have any more changes in mind?

**Comment by utkarshsingx** [comment]
It looks good. I have a color theme in mind for the website. its white and orange( #F56A18). this could be the reference. and then you can take the idea from https://www.swiggy.com/, the login button color can be transparent with grey border and upon hover can change its color to orange, and make logo button margin more to right and login margin to left so that the gap in between is less. Goodluck @yr1404 !

**Comment by yr1404** [comment]
Okay! I'll make the changes
